// npmPackages/fhircast-module/client/components/AuditEventsColumn.jsx

import React from 'react';
import {
  Card, CardHeader, CardContent,
  Typography, Alert, AlertTitle
} from '@mui/material';
import SecurityIcon from '@mui/icons-material/Security';

// =============================================================================
// AUDIT EVENTS COLUMN (Stub)
// =============================================================================

function AuditEventsColumn() {
  return (
    <Card sx={{ bgcolor: 'background.paper', height: '100%' }}>
      <CardHeader
        avatar={<SecurityIcon color="primary" />}
        title="Audit Events"
        sx={{
          borderBottom: 1,
          borderColor: 'divider',
          '& .MuiCardHeader-title': {
            fontSize: '1.1rem'
          }
        }}
      />
      <CardContent>
        <Alert severity="info" sx={{ mb: 2 }}>
          <AlertTitle>HIPAA Audit Trail</AlertTitle>
          AuditEvent records will appear here when the HIPAA subscriber is active.
          Configure <code>settings.private.recordLifecycle.hipaaSubscriber</code> to enable.
        </Alert>
        <Typography variant="body2" sx={{ color: 'text.secondary' }}>
          This column shows AuditEvent FHIR resources generated by the Record Lifecycle
          system. Each record lifecycle event (originate, amend, attest, etc.) produces
          a corresponding AuditEvent for compliance tracking.
        </Typography>
      </CardContent>
    </Card>
  );
}

export default AuditEventsColumn;
